### PR TITLE
Fix #54, Remove unnecessary parentheses around return values.

### LINKED ISSUE #54: Scrub use of () in return statements
**Checklist**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [x] I performed a cursory search to see if the bug report is relevant, not redundant, nor in conflict with other tickets.

**Describe the bug**
Unnecessary parentheses around return values in SC
Copy of https://github.com/nasa/osal/issues/866

**Reporter Info**
@thnkslprpt

### PR DESCRIPTION
**Pull request by thnkslprpt**
**Checklist (Please check before submitting)**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/osal/blob/main/CONTRIBUTING.md).
* [x] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
- Fixes #54 
  - Removes parentheses in return statements in SC that return a single value/term.

This aligns these return statements with the predominant style of cFS.

**Testing performed**
None, prior to submission of the pull request.

**Expected behavior changes**
No impact on behavior.

**Contributor Info - All information REQUIRED for consideration of pull request**
@thnkslprpt

### CODE REVIEW

**Comment by thnkslprpt** [comment]
> @thnkslprpt Would you be able to resolve the conflicts?

I think it's resolved now.
I added another commit to fix the rest of the cases (of parentheses around return values) that were introduced after the merge conflict resolution.
Should I squash those commits together now?

**Comment by dzbaker** [comment]
> > @thnkslprpt Would you be able to resolve the conflicts?
> 
> I think it's resolved now. I added another commit to fix the rest of the cases (of parentheses around return values) that were introduced after the merge conflict resolution. Should I squash those commits together now?

Thanks! That would be good. I'll add this to the CCB agenda for today just so everyone can take a quick look since the scope increased a bit.

**Comment by dzbaker** [comment]
@thnkslprpt CCB 6 October 2022: Approved pending resolution of failed workflow checks.

**Comment by dzbaker** [comment]
@thnkslprpt Would you be able to squash together the commits (so the commit message check passes)?

**Comment by thnkslprpt** [comment]
> @thnkslprpt Would you be able to squash together the commits (so the commit message check passes)?

Hi @dzbaker - I may need a bit of a hand with that...
I tried a few times but just ended up tying myself in knots.
image

**Comment by dzbaker** [comment]
> > @thnkslprpt Would you be able to squash together the commits (so the commit message check passes)?
> 
> Hi @dzbaker - I may need a bit of a hand with that... I tried a few times but just ended up tying myself in knots. image

@thnkslprpt Hmm, that's odd. Are you able to change the commit message for the merge commit (using "git commit --amend") instead?

**Comment by thnkslprpt** [comment]
> @thnkslprpt Hmm, that's odd. Are you able to change the commit message for the merge commit (using "git commit --amend") instead?

I couldn't get it working in the original local git repository I used for these changes, but by opening a clean folder and cloning it in again, git finally let me amend the commit message of the merge commit. Still didn't let me squash them together, though...

**Comment by thnkslprpt** [comment]
Happy to just close this PR and open a new one with a single commit - might make things easier.

**Pull request merged**
